apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piwigo-mariadb-backups
  namespace: piwigo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
