apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: piwigo-mariadb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mariadb
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m0s
  targetNamespace: piwigo
  values:
    primary:
      persistence:
        size: 5Gi
    auth:
      username: piwigo
