apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piwigo-data
  namespace: piwigo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
