apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piwigo-config
  namespace: piwigo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mb
  storageClassName: local-path
