apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- config.pvc.yaml
- statefulset.yaml
- service.yaml
- piwigo-s3-backup.sealed_secret.yaml
- mariadb/helm.release.yaml
