apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: piwigo
  namespace: piwigo
  labels:
    app: piwigo
spec:
  serviceName: piwigo
  selector:
    matchLabels:
      app: piwigo
  template:
    metadata:
      labels:
        app: piwigo
    spec:
      containers:
      - name: piwigo
        image: ghcr.io/linuxserver/piwigo
        ports:
        - containerPort: 80
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        volumeMounts:
        - name: data
          mountPath: /config
      - name: piwigo-s3-backup
        image: lobaro/restic-backup-docker:1.2-0.9.4
        env:
        - name: RESTIC_REPOSITORY
          value: s3:https://s3.us-west-1.wasabisys.com/gallery.enigmacurry.com
        # Restic /requires/ encryption, but I don't need it, and I worry more
        # about forgetting the password than anything else. Data is protected by
        # S3 credentials not encryption. The hard coded `password` here is cool:
        - name: RESTIC_PASSWORD
          value: password
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: piwigo-s3-backup
              key: S3_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: piwigo-s3-backup
              key: S3_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: piwigo-data
