apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: piwigo
  namespace: piwigo
  labels:
    app: piwigo
spec:
  serviceName: piwigo
  selector:
    matchLabels:
      app: piwigo
  template:
    metadata:
      labels:
        app: piwigo
    spec:
      containers:
      - name: piwigo
        image: ghcr.io/linuxserver/piwigo
        ports:
        - containerPort: 80
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: piwigo-config
