apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgresql
      version: 10.1.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m0s
  targetNamespace: postgres
  values:
    persistence:
      size: 1Gi
    postgresqlDatabase: pyapp
    postgresqlUsername: pyapp
